### PR TITLE
implement golangci-lint feature and fix linter Errors

### PR DESCRIPTION
**Pull request by viveksahu26**
### Why we need this ?
This pull request introduces a comprehensive `golangci-lint` CI/CD pipeline setup to enforce coding standards and improve code quality across the project. Let's understand why we need this:
- whether it's a maintainer or a contributor everyone does mistake on revieving code or writing code respectively from coding perspective because no one is perfect. These are not big mistakes but a tiny mistakes but important such as:
  - not following CamelCase for writing variable names.
  - not handling error after error is being thrown and hide it with "_" variable
  - providing more permission on writing files than it requires
  - not formatting the code according to the standard of the project
  - mis-spelled of some variables or function
  - not making use of arguments passed in the function
  - declared variables, imports, or functions  but not used
  - leaving a blank line or whitespace
  - and many such things.

To handle such errors golang provides wide range of [linters](https://github.com/golangci/awesome-go-linters) i.e. 50+ linters such as `gofmt`, `govet`, and many more mentioned [here](https://github.com/golangci/awesome-go-linters). But  no one want to  import each one of them in your package manually. Therefore, to solve this we have [golangci-lint](https://golangci-lint.run/). It is the preferred Go linters aggregator that covers most the linters you’ll ever need. It runs these linters in parallel and reuses the build cache for improved performance during development. 

### What changes are being made ?
- Added `golangci-lint.yaml` with configured linters and settings in a github worflow, which will be triggered on each PR made to the main branch.
- Added the configuration file of `golangci-lint`  in `golangci.yml` to include linting steps and all linters to process.
- Ran locally these errors and resolved all the  identified linting errors to adhere to the new standards and configurations.

### Resources:
- https://golangci-lint.run/
- https://golangci-lint.run/welcome/install/#github-actions

### CODE REVIEW

**Review by riteshnoronha — APPROVED** [review]

**Comment by riteshnoronha** [comment]
@viveksahu26 need to resolve conflicts

**Comment by viveksahu26** [comment]
Hey @riteshnoronha , any update on this ?

**Comment by riteshnoronha** [comment]
@viveksahu26 lets resolve the conflicts then we can merge this in

**Comment by viveksahu26** [comment]
Hey @riteshnoronha , merged conflict is resolved now !!

**Review by riteshnoronha — APPROVED** [review]

**Pull request merged**
