### PR TITLE
support platform arm64

### LINKED ISSUE #305: Support Image for Apple M chips
```
docker run  ghcr.io/interlynk-io/sbomqs score
Unable to find image 'ghcr.io/interlynk-io/sbomqs:latest' locally
latest: Pulling from interlynk-io/sbomqs
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help
```

### PR DESCRIPTION
**Pull request by viveksahu26**
closes #305 

This PR add image support for `arm64` platform along with `amd64`.

### CODE REVIEW

**Comment by riteshnoronha** [comment]
Yes we need this change. However i had to remove it since https://github.com/interlynk-io/sbomqs/blob/main/Dockerfile#L19 also needs to be changed to support ARM.

**Comment by viveksahu26** [comment]
Hey @riteshnoronha, What about migrating from Dockerfile to [ko](https://ko.build/) ? As ko makes [multi-platform builds](https://ko.build/features/multi-platform/) easy,

**Comment by viveksahu26** [comment]
Hey @riteshnoronha , check this [packages](https://github.com/viveksahu26/sbomqs/pkgs/container/sbomqs). i have released it in my cloned repo.

**Review by riteshnoronha — APPROVED** [review]
Looks good.

**Pull request merged**
